#Speed of the Slow Vector Plate (default)
# Default: 0.05
# Range: 0.0 ~ 10.0
slowVectorSpeed = 0.05
#Speed of the Moderate Vector Plate
# Default: 0.1
# Range: 0.0 ~ 10.0
moderateVectorSpeed = 0.1
#Speed of the Fast Vector Plate
# Default: 0.2
# Range: 0.0 ~ 10.0
fastVectorSpeed = 0.2
#Speed of the Extreme Vector Plate
# Default: 0.4
# Range: 0.0 ~ 10.0
extremeVectorSpeed = 0.4
#Speed of the Ultra Vector Plate
# Default: 0.8
# Range: 0.0 ~ 10.0
ultraVectorSpeed = 0.8
