#Speed of the Slow Vector Plate
# Default: 0.1
# Range: 0.0 ~ 100.0
0_slowVectorSpeed = 0.1
#Speed of the Moderate Vector Plate
# Default: 0.5
# Range: 0.0 ~ 100.0
1_moderateVectorSpeed = 0.5
#Speed of the Fast Vector Plate
# Default: 1.0
# Range: 0.0 ~ 100.0
2_fastVectorSpeed = 1.0
#Speed of the Extreme Vector Plate
# Default: 5.0
# Range: 0.0 ~ 100.0
4_extremeVectorSpeed = 5.0
#Speed of the Ultra Vector Plate
# Default: 15.0
# Range: 0.0 ~ 100.0
4_ultraVectorSpeed = 15.0
#Amount of energy consumed by the Hellfire Igniter
# Default: 10
# Range: > 0
5_hellfireIgniterConsume = 10
#Quantity of energy the Hellfire Igniter can be stored
# Default: 1000
# Range: > 0
6_hellfireIgniterBuffer = 1000
